name: terraform
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  id-token: write # required for OIDC
  contents: read # required for actions/checkout

jobs:
  terraform:
    name: terraform install, init, plan, apply
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_NUMBER}}:role/github-actions-terraform-uoy
          role-session-name: GitHubActions
          aws-region: eu-west-2

      - name: verify authentication
        run: aws sts get-caller-identity

      - name: terraform install
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: terraform format
        run: terraform fmt -check

      - name: terraform init
        run: terraform init

      - name: terraform validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve
